-- =============================================================================
-- Book Corner Online Bookstore - PostgreSQL Database Initialization Script
-- Executed on initial container bootstrap by /docker-entrypoint-initdb.d/
-- =============================================================================

\connect bookcorner;

-- 1. Enable Required High-Performance Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "btree_gin";

-- 2. Create Isolated Domain Schemas
CREATE SCHEMA IF NOT EXISTS member;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS ordering;
CREATE SCHEMA IF NOT EXISTS payment;
CREATE SCHEMA IF NOT EXISTS shipping;
CREATE SCHEMA IF NOT EXISTS store;
CREATE SCHEMA IF NOT EXISTS review;

-- 3. Set Schema Search Path and Timezone Defaults
ALTER DATABASE bookcorner SET timezone TO 'UTC';
ALTER DATABASE bookcorner SET search_path TO public, member, catalog, ordering, payment, shipping, store, review;

-- 4. Grant Permissions to Application Role
GRANT ALL PRIVILEGES ON SCHEMA public TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA member TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA catalog TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA ordering TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA payment TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA shipping TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA store TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA review TO CURRENT_USER;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO CURRENT_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA member TO CURRENT_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA catalog TO CURRENT_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ordering TO CURRENT_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA payment TO CURRENT_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA shipping TO CURRENT_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA store TO CURRENT_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA review TO CURRENT_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA member GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA ordering GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA payment GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA shipping GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA store GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA review GRANT ALL ON TABLES TO CURRENT_USER;
