package com.bookcorner.common.exception;

import com.bookcorner.dto.common.ErrorEnvelope;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.net.URI;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Enterprise-grade RFC-7807 / RFC-9457 compliant Problem Details representation.
 * Provides standard machine-readable and human-readable details for HTTP API errors,
 * alongside custom enterprise extensions (code, requestId, timestamp, invalidParams).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ProblemDetails implements Serializable {

    /**
     * A URI reference that identifies the problem type [RFC7807 Section 3.1].
     */
    @Builder.Default
    private URI type = URI.create("urn:bookcorner:problem:generic");

    /**
     * A short, human-readable summary of the problem type.
     */
    private String title;

    /**
     * The HTTP status code generated by the origin server for this occurrence.
     */
    private Integer status;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    private String detail;

    /**
     * A URI reference that identifies the specific occurrence of the problem (e.g. request URI).
     */
    private URI instance;

    /**
     * Domain-specific, machine-readable alphanumeric error code (e.g. INSUFFICIENT_STOCK).
     */
    private String code;

    /**
     * Distributed trace or request correlation ID for observability.
     */
    @Builder.Default
    private String requestId = UUID.randomUUID().toString();

    /**
     * UTC timestamp when the error occurred.
     */
    @Builder.Default
    private Instant timestamp = Instant.now();

    /**
     * Field-level validation constraints that failed, if applicable.
     */
    @Builder.Default
    private List<InvalidParam> invalidParams = new ArrayList<>();

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class InvalidParam implements Serializable {
        private String name;
        private String reason;
        private Object rejectedValue;

        public static InvalidParam of(String name, String reason) {
            return InvalidParam.builder()
                    .name(name)
                    .reason(reason)
                    .build();
        }

        public static InvalidParam of(String name, String reason, Object rejectedValue) {
            return InvalidParam.builder()
                    .name(name)
                    .reason(reason)
                    .rejectedValue(rejectedValue)
                    .build();
        }
    }

    /**
     * Compatibility accessor providing 'success: false' for OpenAPI ErrorEnvelope consumers.
     */
    public boolean isSuccess() {
        return false;
    }

    /**
     * Compatibility accessor providing nested 'error' block for OpenAPI ErrorEnvelope consumers.
     */
    public ErrorEnvelope.ErrorDetail getError() {
        List<ErrorEnvelope.FieldErrorDetail> details = invalidParams != null
                ? invalidParams.stream()
                    .map(ip -> ErrorEnvelope.FieldErrorDetail.builder()
                            .field(ip.getName())
                            .issue(ip.getReason())
                            .build())
                    .collect(Collectors.toList())
                : java.util.Collections.emptyList();

        return ErrorEnvelope.ErrorDetail.builder()
                .code(code != null ? code : "ERROR_" + status)
                .message(detail != null ? detail : title)
                .details(details)
                .timestamp(timestamp)
                .requestId(requestId)
                .build();
    }

    /**
     * Converts this ProblemDetails instance to the OpenAPI-compliant ErrorEnvelope schema.
     */
    public ErrorEnvelope toErrorEnvelope() {
        return ErrorEnvelope.builder()
                .success(false)
                .error(getError())
                .build();
    }
}
